[[plugins]]
repo  = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # カラースキーマ
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  " au MyAutoCmd VimEnter * nested colorscheme hybrid
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'gkjgh/cobalt'

[[plugins]]
repo = 'vim-scripts/Risto-Color-Scheme'


[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'bling/vim-bufferline'

#[[plugins]]
#repo = 'vim-scripts/buftabs'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'vim-scripts/ruby-matchit'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'ElmCast/elm-vim'
